services:
  redis:
    image: redis
    container_name: chat_redis
    ports:
      - 6379:6379
    volumes:
      - "./redis_data:/data"
  rabbitmq:
    image: rabbitmq:3.8.9-management
    container_name: chat_queue
    restart: always
    tty: true
    stdin_open: true
    # volumes:
    #   - ./enable_plugins:/etc/rabbitmq/enabled_plugins:ro
    ports:
      # HTTP DASHBOARD FOR MANAGEMENT
      - "15672:15672"
      # AMQP PROTOCOL
      - "5672:5672"
      # MQTT PROTOCOL
      #- "1883:1883"
      # MQTT OVER WEBSOCKETS
      #- "15675:15675"
